version: '3'

# 网桥redis -> 方便相互通讯
networks:
  redis:
    ipam:
      driver: default
      config:
        - subnet: "172.28.0.0/24"

services:
  redis-6381:
    image: redis:7.0.5 # 使用官方镜像
    container_name: redis-6381 # 容器名为'redis-6381'
    restart: unless-stopped # 指定容器退出后的重启策略为始终重启
    command: redis-server /etc/redis/redis.conf --port 6381 --requirepass 123456 --appendonly yes --cluster-enabled yes
    environment:
      TZ: Asia/Shanghai
      LANG: en_US.UTF-8
    volumes:
      - "./redis-cluster/redis-6381/data:/data"
      - "./redis-cluster/redis-6381/config/redis.conf:/etc/redis/redis.conf"
    ports:
      - "6381:6381"
      - "16381:16381" # 集群总线端口
    networks:
      redis:
        ipv4_address: 172.28.0.11
  redis-6382:
    image: redis:7.0.5
    container_name: redis-6382
    restart: unless-stopped
    command: redis-server /etc/redis/redis.conf --port 6382 --requirepass 123456 --appendonly yes --cluster-enabled yes
    environment:
      TZ: Asia/Shanghai
      LANG: en_US.UTF-8
    volumes:
      - "./redis-cluster/redis-6382/data:/data"
      - "./redis-cluster/redis-6382/config/redis.conf:/etc/redis/redis.conf"
    ports:
      - "6382:6382"
      - "16382:16382" # 集群总线端口
    networks:
      redis:
        ipv4_address: 172.28.0.12
  redis-6383:
    image: redis:7.0.5
    container_name: redis-6383
    restart: unless-stopped
    command: redis-server /etc/redis/redis.conf --port 6383 --requirepass 123456 --appendonly yes --cluster-enabled yes
    environment:
      TZ: Asia/Shanghai
      LANG: en_US.UTF-8
    volumes:
      - "./redis-cluster/redis-6383/data:/data"
      - "./redis-cluster/redis-6383/config/redis.conf:/etc/redis/redis.conf"
    ports:
      - "6383:6383"
      - "16383:16383" # 集群总线端口
    networks:
      redis:
        ipv4_address: 172.28.0.13
  redis-6384:
    image: redis:7.0.5
    container_name: redis-6384
    restart: unless-stopped
    command: redis-server /etc/redis/redis.conf --port 6384 --requirepass 123456 --appendonly yes --cluster-enabled yes
    environment:
      TZ: Asia/Shanghai
      LANG: en_US.UTF-8
    volumes:
      - "./redis-cluster/redis-6384/data:/data"
      - "./redis-cluster/redis-6384/config/redis.conf:/etc/redis/redis.conf"
    ports:
      - "6384:6384"
      - "16384:16384" # 集群总线端口
    networks:
      redis:
        ipv4_address: 172.28.0.14
  redis-6385:
    image: redis:7.0.5
    container_name: redis-6385
    restart: unless-stopped
    command: redis-server /etc/redis/redis.conf --port 6385 --requirepass 123456 --appendonly yes --cluster-enabled yes
    environment:
      TZ: Asia/Shanghai
      LANG: en_US.UTF-8
    volumes:
      - "./redis-cluster/redis-6385/data:/data"
      - "./redis-cluster/redis-6385/config/redis.conf:/etc/redis/redis.conf"
    ports:
      - "6385:6385"
      - "16385:16385" # 集群总线端口
    networks:
      redis:
        ipv4_address: 172.28.0.15
  redis-6386:
    image: redis:7.0.5
    container_name: redis-6386
    restart: unless-stopped
    command: redis-server /etc/redis/redis.conf --port 6386 --requirepass 123456 --appendonly yes --cluster-enabled yes
    environment:
      TZ: Asia/Shanghai
      LANG: en_US.UTF-8
    volumes:
      - "./redis-cluster/redis-6386/data:/data"
      - "./redis-cluster/redis-6386/config/redis.conf:/etc/redis/redis.conf"
    ports:
      - "6386:6386"
      - "16386:16386" # 集群总线端口
    networks:
      redis:
        ipv4_address: 172.28.0.16

  # 用于测试加入新节点
  redis-6388:
    image: redis:7.0.5
    container_name: redis-6388
    restart: unless-stopped
    command: redis-server /etc/redis/redis.conf --port 6388 --requirepass 123456 --appendonly yes --cluster-enabled yes
    environment:
      TZ: Asia/Shanghai
      LANG: en_US.UTF-8
    volumes:
      - "./redis-cluster/redis-6388/data:/data"
      - "./redis-cluster/redis-6388/config/redis.conf:/etc/redis/redis.conf"
    ports:
      - "6388:6388"
      - "16388:16388" # 集群总线端口
    networks:
      redis:
        ipv4_address: 172.28.0.18
