services:
  postgresql:
    image: postgres:14.5
    container_name: postgresql
    environment:
      POSTGRES_PASSWORD: 123456
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ~/data/postgresql:/var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: always
