services:
  postgresql:
    image: registry.cn-hangzhou.aliyuncs.com/zhengqing/postgres:14.5
    container_name: postgresql
    environment:
      POSTGRES_PASSWORD: 123456
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - /mnt/mk_data/database/postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    user: 999:999